import Head from "next/head";
import Avatar from "../components/Avatar";
import Footer from "../components/Footer";
import Image from "next/image";
import { MicrophoneIcon, ViewGridIcon } from "@heroicons/react/solid";
import { SearchIcon } from "@heroicons/react/outline";
import { useRef } from "react";
import { useRouter } from "next/router";
export default function Home() {
  const searchInputRef = useRef(null);
  const router = useRouter();
  const search = (e) => {
    e.preventDefault();

    const term = searchInputRef.current.value;
    if (!term || term.trim().length === 0) return;

    router.push(`/search?term=${term}`);
  };
  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* HEADER */}
      <header className="flex w-full justify-between p-5 text-sm text-[#fff]">
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
          <ViewGridIcon className="h-10 w-10 p-2 cursor-pointer rounded-full hover:bg-gray-700 transition-all duration-200" />
          <Avatar url="https://github.com/frans203.png" />
        </div>
      </header>
      {/* BODY */}
      <form className="flex flex-col items-center flex-grow justify-center w-4/5">
        <Image
          src="https://www.google.com.br/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
          width="272"
          height="92"
        />
        <div className="flex space-x-4 w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-lg border-gray-600 border rounded-3xl p-3 focus-within:bg-[#303134] px-5 py-3 sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="text-[#fff] h-6 cursor-pointer" />
          <input
            type="text"
            ref={searchInputRef}
            className="focus:outline-none flex-grow bg-transparent text-[#fff]"
          />
          <MicrophoneIcon className="h-6 text-[#fff] cursor-pointer" />
        </div>

        <div className="flex flex-col w-1/2 space-y-2 mt-8 items-center justify-center sm:space-y-0 sm:space-x-4 sm:flex-row">
          <button className="btn" onClick={search}>
            Google Search
          </button>
          <button className="btn" onClick={search}>
            I'm Feeling Lucky
          </button>
        </div>
      </form>
      {/* FOOTER */}
      <Footer />
    </div>
  );
}
